### ISSUE TITLE
Migrate tab controls in user and role modals to @angular/material

### ISSUE THREAD

**Issue by lprichar** [vdurante/module-zero-core-template#11]

**Comment by lprichar** [comment]
Oh, I had some time booked for this tonight.  Guess I'll use the time to review.

**Comment by iyilm4z** [comment]
@lprichar  thanks! waiting.

**Comment by lprichar** [comment]
Actually @iyilm4z I don't see an open PR or anything tagged to this issue, what review did you want me to perform?

**Comment by iyilm4z** [comment]
Dear @lprichar few seconds ago i did another commit. please pull everything and make a general review about everything we have done so far. i think we are so close to make a pull request to orgin repo.

**Comment by lprichar** [comment]
Reviewing now.  I have an site that's pretty close origin/develop that I can compare to, so I can help look for UI discrepancies to help keep this as close to a pure refactor as possible.

**Comment by lprichar** [comment]
Review complete, everything looks great!  This is a fantastic contribution.  Well done guys.  I made a couple of minor changes and submitted them as PR #23.
