### ISSUE TITLE
Replace jquery in user and role checkboxes

### ISSUE THREAD

**Issue by lprichar** [vdurante/module-zero-core-template#14]
e.g. This remove this in create-user.component.ts:

```
$(this.modalContent.nativeElement).find("[name=role]").each((ind:number, elem:Element) => {
            if($(elem).is(":checked") == true){
                roles.push(elem.getAttribute("value").valueOf());
            }
        });
```

**Comment by iyilm4z** [comment]
@lprichar i already did it. [Here](https://github.com/vdurante/module-zero-core-template/blob/9dded8a7c75e6d14ae4b8d1e54a1c3a5058f6979/angular/src/app/roles/create-or-edit-role-dialog.component.ts#L99) it is.

**Comment by lprichar** [comment]
Oh, I see you did already remove the jQuery @iyilm4z, nice!
