### ISSUE TITLE
Migrate roles page to @angular/material components

### ISSUE THREAD

**Issue by vdurante** [vdurante/module-zero-core-template#9]

**Comment by vdurante** [comment]
Creation and edition are the modals. Roles page is the /app/roles page
containing the list of roles. I guess you did both already, right?

**Comment by iyilm4z** [comment]
@vdurante Yes bro did. But please take a look at my last commit. I merged create and edit components which i usually do. But i'm not sure about doing this. As @lprichar said this can be bad. But i did it only showing you guys how it looks like.

**Comment by vdurante** [comment]
@iyilm4z let's to the following: let's ignore the merge of creation and edition for now. As Lee suggested, making such changes makes it hard for the maintainers of abp to approve the commit. Later on you can make the pull request directly to the master repo.

**Comment by iyilm4z** [comment]
@vdurante we are agreed.

**Comment by lprichar** [comment]
I just got latest and I can't run the app.  Getting errors in  `roles.component.html`, is it working for you all?

**Comment by lprichar** [comment]
nm, you're too fast for me, it's already fixed :)
